language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

script: yarn run lint && yarn run test --no-watch --passWithNoTests && yarn run build
after_success: yarn run release

branches:
  only:
    - master
